// PluginManifest — the single source of identity for a scaffolded plugin.
// The scaffolded project's business layer (src/plugin/manifest.ts) exports a
// `manifest` object of this shape; the framework (CLI, installer, MCP server,
// hook build, generator) consumes it and never hard-codes plugin-specific
// strings. Everything the installer writes (markers, config dir, command
// names, tool names, version pins) derives from here.
//
// Two files carry identity: this manifest + package.json. Everything else
// (plugin.json / mcp.json / .mcp.json / marketplace.json) is generated by
// build.mjs from the manifest and committed, so the repo stays a valid
// plugin install source.

/** One config field the framework manages (file + env + precedence + mask). */
export interface ConfigField {
  /** Config key, e.g. "baseUrl". */
  key: string;
  /** Human label for the wizard, e.g. "Base URL". */
  label: string;
  type: "string" | "number" | "boolean" | "json";
  /** Environment variable that overrides the file value, e.g. "VISION_BASE_URL". */
  env: string;
  /** Optional default (built-in defaults are the lowest precedence layer). */
  default?: string | number | boolean;
  /** Mask the value in `config get` output (secrets). */
  mask?: boolean;
  /** Skip this field in the install wizard's config prompt (managed elsewhere). */
  wizardHidden?: boolean;
  /** Free-text placeholder shown in the wizard prompt. */
  placeholder?: string;
}

/** One MCP tool the plugin exposes to agent clients. */
export interface ToolDef {
  name: string;
  description: string;
  inputSchema: Record<string, unknown>;
  /** Tool implementation; ctx carries config access + logging. */
  handler: (args: Record<string, unknown>, ctx: ToolContext) => Promise<unknown>;
}

export interface ToolContext {
  /** Resolved config values keyed by field.key. */
  config: Record<string, string | number | boolean | undefined>;
  /** Log a line to stderr (never stdout — breaks MCP stdio). */
  log: (msg: string) => void;
}

/** Result a hook handler returns; `{}` (no-op) means the tool proceeds. */
export interface HookResult {
  decision?: "block";
  hookSpecificOutput?: {
    hookEventName?: string;
    additionalContext?: string;
  };
}

export interface HookContext {
  cwd: string;
  config: Record<string, string | number | boolean | undefined>;
  log: (msg: string) => void;
}

export interface HookDef {
  /** PreToolUse handler: receives the hook event, returns block/no-op. */
  preToolUse?: (input: Record<string, unknown>, ctx: HookContext) => Promise<HookResult>;
  /** SessionStart handler: returns context injection or no-op. */
  sessionStart?: (input: Record<string, unknown>, ctx: HookContext) => Promise<HookResult>;
}

/** Endpoint presets for the install wizard (openrouter-style "Decide later" last). */
export interface Preset {
  id: string;
  label: string;
  values: Record<string, string | number | boolean>;
}

/** One doctor check contributed by the business layer. */
export interface DoctorCheck {
  id: string;
  label: string;
  /** Return problems (empty = ok). */
  run: (config: Record<string, string | number | boolean | undefined>) => Promise<string[]>;
}

/** Identity markers. MUST be stable across releases (uninstall relies on
 *  them; files without them are never touched). Decoupled from `name` on
 *  purpose — see the publishing guide: a rename never changes markers. */
export interface IdentityMarkers {
  /** Hook bundle banner (`/*! <marker> *\/`), checked by uninstall. */
  hook: string;
  /** Substring inside settings.json hook command strings that identifies OUR entries. */
  hookCommand: string;
  /** SKILL.md frontmatter marker line (doubles as provenance). */
  skill: string;
  /** Slash-command file marker. */
  command: string;
  /** Slash-command filename, e.g. "vision.md". */
  commandFile: string;
  /** Skill dir name, e.g. "deepseek-vision". */
  skillDir: string;
  /** Config dir name, e.g. ".deepseek-vl". */
  configDir: string;
  /** Cursor local plugin dir name. */
  cursorDir: string;
  /** Cursor marker file name inside the plugin dir. */
  cursorMarkerFile: string;
  /** Cursor marker string. */
  cursorMarker: string;
  /** AGENTS.md managed block start marker, e.g. "<!-- deepseek-vl:start -->". */
  agentsStart: string;
  /** AGENTS.md managed block end marker. */
  agentsEnd: string;
}

export interface PluginManifest {
  /** npm package name — also the CLI bin name (npx resolves it). */
  name: string;
  /** Current version; CLI `--version`, MCP serverInfo, plugin.json and
   *  marketplace.json are all injected from this by build.mjs. */
  version: string;
  /** Display brand, e.g. "DeepSeek Vision". */
  brand: string;
  /** One-line package description. */
  description: string;
  /** GitHub slug for git-source install hints, e.g. "limccn/deepseek-vl-support". */
  githubSlug?: string;
  /** Stable identity markers (see above). */
  markers: IdentityMarkers;
  /** Config fields managed by the framework. */
  config: ConfigField[];
  /** Optional endpoint presets for the wizard. */
  presets?: Preset[];
  /** MCP tools exposed to agent clients. */
  tools: ToolDef[];
  /** Skill file shipped to agents (content comes from assets; filename here). */
  skill?: { filename: string };
  /** Claude Code hook handlers (built into dist/hook.cjs by build.mjs). */
  hook?: HookDef;
  /** Extra CLI subcommands contributed by the business layer. */
  bizCli?: Record<string, (argv: string[], ctx: BizCliContext) => Promise<void>>;
  /** Business doctor checks run by `doctor`. */
  doctorChecks?: DoctorCheck[];
}

export interface BizCliContext {
  log: (msg: string) => void;
  fail: (msg: string) => never;
}

/** Default markers derived from a package name — scaffolds call this with
 *  their own values instead; kept here for generators and tests. */
export function defaultMarkers(pkgName: string): IdentityMarkers {
  return {
    hook: `${pkgName}-hook`,
    hookCommand: `${pkgName}-hook`,
    skill: `${pkgName}:skill`,
    command: `${pkgName}:command`,
    commandFile: "vision.md",
    skillDir: pkgName,
    configDir: `.${pkgName}`,
    cursorDir: pkgName,
    cursorMarkerFile: ".agent-plugin-managed",
    cursorMarker: `${pkgName}:managed`,
    agentsStart: `<!-- ${pkgName}:start -->`,
    agentsEnd: `<!-- ${pkgName}:end -->`,
  };
}
