// Scaffold generator: copies the template package into a new project dir and
// rewrites identity + selected scope. The template IS this package — the
// generator lives in the same repo it copies (single-repo single-package
// topology, D5): packaged files include src/, tests/, build.mjs, etc.
//
// Rewrites:
//  1. src/plugin/manifest.ts  — identity (name/brand/slug/markers) + the
//     selected capability fields (tools/hook/bizCli/doctorChecks)
//  2. package.json            — name, bin, description, keywords, version (reset to 0.1.0)
//  3. src/plugin/targets/index.ts — pruned to the selected target set
//  4. tests/                  — capability-owned test files removed for
//     deselected capabilities (target tests self-skip via a runtime guard)
//  5. README.md               — {{placeholder}} tokens filled
//
// Build-generated artifacts (plugin.json, mcp.json, .mcp.json,
// marketplace.json, cordis.patch.yml, assets/, skills/, dist/) are NOT
// copied — the scaffolded project regenerates them on `npm run build`.
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join, sep } from "node:path";
import { fileURLToPath } from "node:url";
import type { GenAnswers } from "./ask.ts";

/** {{placeholder}} fill — same contract as build.mjs (kept local: build.mjs
 *  is a top-level-await script and must not be imported at runtime). */
function fillTemplate(body: string, vars: Record<string, string>): string {
  return body.replace(/\{\{\s*(\w+)\s*\}\}/g, (_, k: string) => vars[k] ?? `{{${k}}}`);
}

// ---------------------------------------------------------------- template set

// Files regenerated by `npm run build` + housekeeping dirs. `.mcp.json` is
// the build copy of mcp.json; `assets/` + `skills/` are build syncs.
// `.agents/.codex/.deepseek-vl/.claude` are per-agent tool/workspace dirs,
// `.github` is the generator's own publish workflow, and `AGENTS.md` /
// `package-lock.json` are dev-workspace residue — all may exist in a dev's
// checkout, and the scaffold must never copy them into a new project.
const EXCLUDED_ROOTS = new Set([
  "node_modules",
  "dist",
  ".git",
  ".trellis",
  ".agents",
  ".codex",
  ".deepseek-vl",
  ".claude",
  ".github",
  "AGENTS.md",
  "package-lock.json",
  "assets",
  "skills",
  "plugin.json",
  "mcp.json",
  ".mcp.json",
  "marketplace.json",
  "cordis.patch.yml",
]);

/** Copy the template package into `dest`, skipping build-generated artifacts
 *  and VCS/housekeeping dirs. */
function copyTemplate(templateRoot: string, dest: string): void {
  mkdirSync(dest, { recursive: true });
  cpSync(templateRoot, dest, {
    recursive: true,
    force: true,
    filter: (p) => {
      const rel = p.slice(templateRoot.length + 1).replace(/[\\/]+$/, "");
      if (rel === "") return true; // the root itself
      const first = rel.split(/[\\/]/)[0] ?? "";
      return !EXCLUDED_ROOTS.has(first);
    },
  });
}

// ---------------------------------------------------------------- manifest.ts

/** Filesystem-safe short name of an npm package: `@scope/xxx` → `xxx`.
 *  Path-ish markers (skillDir / configDir / cursorDir / hook filename) and
 *  the SKILL.md frontmatter `name:` must never contain `/` or `@`; pure
 *  string-content markers (skill / command / agentsStart / agentsEnd) keep
 *  the full scoped name. */
function unscopedName(pkg: string): string {
  return pkg.includes("/") ? pkg.split("/").pop()! : pkg;
}

/** Rewrite src/plugin/manifest.ts: identity from the answers, capability
 *  fields for the selected demo business. Values are literal (no shell
 *  quoting — writeFileSync output), so JSON-stringify every inserted string. */
function rewriteManifest(dir: string, a: GenAnswers): void {
  const j = (s: string): string => JSON.stringify(s);
  const pkg = a.packageName;
  const unscoped = unscopedName(pkg);
  const upper = pkg.replace(/[^a-z0-9]/gi, "_").toUpperCase();
  const lines: string[] = [
    "// Business layer manifest — THE single source of identity for this plugin.",
    "// Generated by create-agent-plugin from the scaffold template; edit freely",
    "// afterwards. Everything the installer writes derives from here.",
    'import type { PluginManifest } from "../framework/manifest.ts";',
  ];
  if (a.capabilities.includes("mcp")) lines.push('import { ping } from "./tools.ts";');
  if (a.capabilities.includes("hook")) lines.push('import { demoHook } from "./hook.ts";');
  if (a.capabilities.includes("cli")) {
    lines.push('import { demoDoctorChecks } from "./doctor.ts";');
    lines.push('import { demoBizCli } from "./cli-business.ts";');
  }
  lines.push("");
  lines.push("export const manifest: PluginManifest = {");
  lines.push(`  name: ${j(pkg)},`);
  lines.push('  version: "0.1.0",');
  lines.push(`  brand: ${j(a.brand)},`);
  lines.push(`  description: ${j(a.description)},`);
  if (a.githubSlug) lines.push(`  githubSlug: ${j(a.githubSlug)},`);
  lines.push("");
  lines.push("  // Identity markers. Keep stable across releases — uninstall recognizes");
  lines.push("  // artifacts by these strings and never touches files without them.");
  lines.push("  markers: {");
  // Path-ish markers take the unscoped short name (no `/`, no `@`); the
  // string-content markers keep the full scoped name.
  lines.push(`    hook: ${j(`${unscoped}-hook`)},`);
  lines.push(`    hookCommand: ${j(`${unscoped}-hook`)},`);
  lines.push(`    skill: ${j(`${pkg}:skill`)},`);
  lines.push(`    command: ${j(`${pkg}:command`)},`);
  lines.push(`    commandFile: ${j("demo.md")},`);
  lines.push(`    skillDir: ${j(unscoped)},`);
  lines.push(`    configDir: ${j(`.${unscoped}`)},`);
  lines.push(`    cursorDir: ${j(unscoped)},`);
  lines.push(`    cursorMarkerFile: ${j(".agent-plugin-managed")},`);
  lines.push(`    cursorMarker: ${j(`${pkg}:managed`)},`);
  lines.push(`    agentsStart: ${j(`<!-- ${pkg}:start -->`)},`);
  lines.push(`    agentsEnd: ${j(`<!-- ${pkg}:end -->`)},`);
  lines.push("  },");
  lines.push("");
  lines.push("  config: [");
  lines.push("    {");
  lines.push(`      key: "greeting",`);
  lines.push(`      label: "Greeting",`);
  lines.push('      type: "string",');
  lines.push(`      env: ${j(`${upper}_GREETING`)},`);
  lines.push(`      default: "Hello, agent!",`);
  lines.push(`      placeholder: ${j(`e.g. Hello from ${a.brand}`)},`);
  lines.push("    },");
  lines.push("    {");
  lines.push(`      key: "token",`);
  lines.push(`      label: "API token",`);
  lines.push('      type: "string",');
  lines.push(`      env: ${j(`${upper}_TOKEN`)},`);
  lines.push("      mask: true,");
  lines.push('      placeholder: "sk-...",');
  lines.push("    },");
  lines.push("  ],");
  lines.push("");
  lines.push(`  tools: ${a.capabilities.includes("mcp") ? "[ping]" : "[]"},`);
  lines.push("");
  lines.push('  // Skill body ships as assets/SKILL.md (byte-synced to skills/<skillDir>/).');
  lines.push('  skill: { filename: "SKILL.md" },');
  if (a.capabilities.includes("hook")) {
    lines.push("");
    lines.push("  hook: demoHook,");
  }
  if (a.capabilities.includes("cli")) {
    lines.push("");
    lines.push("  bizCli: demoBizCli,");
    lines.push("  doctorChecks: demoDoctorChecks,");
  }
  lines.push("};");
  lines.push("");
  writeFileSync(join(dir, "src", "plugin", "manifest.ts"), lines.join("\n"), "utf8");
}

// ---------------------------------------------------------------- package.json

/** Rewrite package.json: name, bin (short name = last scope segment), the
 *  provided description, the package name in keywords, and a fresh 0.1.0
 *  version — the manifest rewrite also resets to 0.1.0, so leaking the
 *  template's own version (e.g. 0.1.0-rc1) would trip the version-equality
 *  test in the scaffolded project. */
function rewritePackageJson(dir: string, a: GenAnswers): void {
  const file = join(dir, "package.json");
  const pkg = JSON.parse(readFileSync(file, "utf8")) as Record<string, unknown>;
  pkg.name = a.packageName;
  pkg.version = "0.1.0";
  (pkg as { bin: Record<string, string> }).bin = {
    [a.packageName.split("/").pop()!]: "dist/cli.js",
  };
  pkg.description = a.description;
  const kw = Array.isArray(pkg.keywords) ? [...(pkg.keywords as string[])] : [];
  if (!kw.includes(a.packageName)) kw.push(a.packageName);
  pkg.keywords = kw;
  writeFileSync(file, JSON.stringify(pkg, null, 2) + "\n", "utf8");
}

// ---------------------------------------------------------------- targets/index.ts

/** Adapter id → (export name, source file) — the stable template layout.
 *  Kept here (not in the framework) because it is a template-structure
 *  contract, not runtime behavior. Sources carry no "./" so the grouping
 *  keys match the file-order list below. */
const TARGET_SOURCES: Record<string, { varName: string; source: string }> = {
  claude: { varName: "claudeAdapter", source: "native-claude.ts" },
  codex: { varName: "codexAdapter", source: "native-codex.ts" },
  opencode: { varName: "opencodeAdapter", source: "native-opencode.ts" },
  qwen: { varName: "qwenAdapter", source: "native-cliagents.ts" },
  reasonix: { varName: "reasonixAdapter", source: "native-cliagents.ts" },
  kilo: { varName: "kiloAdapter", source: "native-cliagents.ts" },
  workbuddy: { varName: "workbuddyAdapter", source: "native-cliagents.ts" },
  devin: { varName: "devinAdapter", source: "native-cliagents.ts" },
  trae: { varName: "traeAdapter", source: "skill-agents.ts" },
  pi: { varName: "piAdapter", source: "skill-agents.ts" },
  omp: { varName: "ompAdapter", source: "skill-agents.ts" },
  dsh: { varName: "dshAdapter", source: "skill-agents.ts" },
  copilot: { varName: "copilotAdapter", source: "plugin-agents.ts" },
  cursor: { varName: "cursorAdapter", source: "plugin-agents.ts" },
  kiro: { varName: "kiroAdapter", source: "plugin-agents.ts" },
  openclaw: { varName: "openclawAdapter", source: "plugin-agents.ts" },
  hermes: { varName: "hermesAdapter", source: "plugin-agents.ts" },
  vscode: { varName: "vscodeAdapter", source: "plugin-agents.ts" },
  "chatgpt-codex": { varName: "chatgptCodexAdapter", source: "plugin-agents.ts" },
  grok: { varName: "grokAdapter", source: "plugin-agents.ts" },
  nanoclaw: { varName: "nanoclawAdapter", source: "plugin-agents.ts" },
  other: { varName: "otherAdapter", source: "plugin-agents.ts" },
};

/** Rewrite src/plugin/targets/index.ts with only the selected targets. */
export function rewriteTargetsIndex(dir: string, targetIds: string[]): void {
  const selected = targetIds.map((id) => {
    const t = TARGET_SOURCES[id];
    if (!t) throw new Error(`unknown target id: ${id}`);
    return { id, ...t };
  });
  // Group imports by source file, preserving the template's file order.
  const order = [
    "native-claude.ts",
    "native-codex.ts",
    "native-opencode.ts",
    "native-cliagents.ts",
    "skill-agents.ts",
    "plugin-agents.ts",
  ];
  const bySource = new Map<string, { id: string; varName: string }[]>();
  for (const s of selected) {
    const list = bySource.get(s.source) ?? [];
    list.push(s);
    bySource.set(s.source, list);
  }
  const lines: string[] = [
    "// Target adapter registry — generated by create-agent-plugin; edit this",
    "// file to change the target set later (see the README \"Adding a target\" guide).",
    'import type { TargetAdapter } from "../../framework/registry.ts";',
  ];
  for (const src of order) {
    for (const s of bySource.get(src) ?? []) {
      lines.push(`import { ${s.varName} } from "./${src}";`);
    }
  }
  lines.push("");
  lines.push("export const adapters: TargetAdapter[] = [");
  for (const s of selected) lines.push(`  ${s.varName},`);
  lines.push("];");
  lines.push("");
  writeFileSync(join(dir, "src", "plugin", "targets", "index.ts"), lines.join("\n"), "utf8");
}

// ---------------------------------------------------------------- capability tests

/** Test files owned by a demo capability — removed when the capability is
 *  deselected (their assertions would fail without the business they test). */
const CAPABILITY_TESTS: Record<string, string[]> = {
  mcp: ["tests/mcp.test.ts"],
  hook: ["tests/hook-protocol.test.ts"],
  cli: ["tests/cli.test.ts"],
};

// ---------------------------------------------------------------- entry

export interface ScaffoldResult {
  dir: string;
  removedTests: string[];
}

/** Template root: the package root containing src/. Bundled into
 *  dist/generator.js that is file → dist → root (two ".."); in the source
 *  tree scaffold.ts is file → generator → src → root (three ".."). */
function findTemplateRoot(): string {
  const self = fileURLToPath(import.meta.url);
  const inDist = self.split(sep).includes("dist");
  return inDist ? join(self, "..", "..") : join(self, "..", "..", "..");
}

/** Generate a new plugin project. `cwd` is where the target dir is created. */
export async function scaffold(a: GenAnswers, cwd: string): Promise<ScaffoldResult> {
  const templateRoot = findTemplateRoot();
  const dest = join(cwd, a.dir);

  if (existsSync(dest)) {
    const entries = readDirNames(dest);
    if (entries.length > 0) {
      throw new Error(
        `target directory already exists and is not empty: ${dest} (${entries.length} entries) — pick another name or remove it`,
      );
    }
  }

  copyTemplate(templateRoot, dest);
  rewriteManifest(dest, a);
  rewritePackageJson(dest, a);
  rewriteTargetsIndex(dest, a.targets);

  // Remove tests owned by deselected capabilities.
  const removedTests: string[] = [];
  for (const [cap, files] of Object.entries(CAPABILITY_TESTS)) {
    if (a.capabilities.includes(cap)) continue;
    for (const rel of files) {
      const p = join(dest, rel);
      if (existsSync(p)) {
        rmSync(p, { force: true });
        removedTests.push(rel);
      }
    }
  }

  // Fill README placeholders (tokens mirror build.mjs vars). Path-ish tokens
  // (skillDir / configDir / hook) take the unscoped short name; {{name}} keeps
  // the full package name (npx commands).
  //
  // The README template is src/assets/README.md, NOT the package-root
  // README.md: the copied root README is already filled ({{name}} → the
  // template's own identity), so a scaffolded project regenerating a new
  // project would copy a placeholder-free README and keep the OLD identity.
  // The asset copy always carries placeholders — scaffolded projects copy it
  // too (src/assets/ ships), so regeneration is identity-safe.
  const readmeTpl = join(templateRoot, "src", "assets", "README.md");
  if (existsSync(readmeTpl)) {
    const unscoped = unscopedName(a.packageName);
    writeFileSync(
      join(dest, "README.md"),
      fillTemplate(readFileSync(readmeTpl, "utf8"), {
        name: a.packageName,
        brand: a.brand,
        version: "0.1.0",
        description: a.description,
        skillDir: unscoped,
        configDir: `.${unscoped}`,
        hook: `${unscoped}-hook`,
        commandFile: "demo.md",
      }),
      "utf8",
    );
  }

  return { dir: dest, removedTests };
}

/** Print the next steps for the scaffolded project. */
export function printNextSteps(a: GenAnswers, dest: string): void {
  const caps = a.capabilities.join(" + ") || "(none — framework only)";
  process.stdout.write(
    [
      "",
      `Generated ${a.brand} (${a.packageName}) at ${dest}`,
      `  capabilities : ${caps}`,
      `  targets      : ${a.targets.length} — ${a.targets.join(", ")}`,
      "",
      "Next steps:",
      `  cd ${dest}`,
      "  npm install",
      "  npm run verify        # build + typecheck + test",
      `  npm run build && npm pack --dry-run   # manifest check`,
      "",
      "Then fill in the business layer (see README \"What to replace\"):",
      "  src/plugin/tools.ts      — your real MCP tools",
      "  src/plugin/hook.ts       — your real hook handlers",
      "  src/plugin/doctor.ts     — your real doctor checks",
      "  src/plugin/cli-business.ts — your CLI subcommands",
      "",
      "Publishing: bump version in src/plugin/manifest.ts (build injects it",
      "into plugin.json / marketplace.json), commit, and `npm publish`.",
      "",
    ].join("\n"),
  );
}

function readDirNames(p: string): string[] {
  try {
    return readdirSync(p);
  } catch {
    return [];
  }
}
